"""job_get_java — View the generated Java code for a job."""

from __future__ import annotations

from talend_mcp.tools._base import error_response, json_response


def register(mcp, services):
    @mcp.tool()
    async def job_get_java(
        job_name: str,
        project: str | None = None,
    ) -> str:
        """View the generated Java source code for a Talend job.

        The Java code is generated by Talend Studio when the job is built.
        It may not exist if the job hasn't been compiled.

        Args:
            job_name: Name of the job
            project: Project name (uses default if omitted)
        """
        services.audit.log("job_get_java", {"job_name": job_name, "project": project})
        try:
            java_code = await services.workspace.find_generated_java(project, job_name)
            if java_code is None:
                return error_response(
                    f"Generated Java not found for job '{job_name}'. "
                    "The job may not have been built yet.",
                    "NOT_FOUND",
                )

            # Truncate if very large
            if len(java_code) > 50000:
                java_code = java_code[:50000] + "\n// ... (truncated, file too large)"

            return json_response({
                "job_name": job_name,
                "java_code": java_code,
                "length": len(java_code),
            })
        except FileNotFoundError as e:
            return error_response(str(e), "NOT_FOUND")
